#Template will not run with as is, only meant as a sample to describe CloudFormation template anatomy 
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This is my template description!'
#Defines two parameters, KeyName and EnvType
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must specify prod or test.
#Look up table for AMI ID based on AWS Region and OS virtualization architecture
Mappings: 
  RegionMap: 
    us-east-1:
      HVM64: ami-0ff8a91507f77f867
      HVMG2: ami-0a584ac55a7631c0c
    us-west-1:
      HVM64: ami-0bdb828fd58c52235
      HVMG2: ami-066ee5fd4a9ef77f1
    eu-west-1:
      HVM64: ami-047bb4163c506cd98
      HVMG2: ami-0a7c483d527806435
    ap-northeast-1:
      HVM64: ami-06cd52961ce9f0d85
      HVMG2: ami-053cdd503598e4a9d
    ap-southeast-1:
      HVM64: ami-08569b978cc4dfa10
      HVMG2: ami-0be9df32ae9f92309
Conditions:
  #The isProduction condition checks if the EnvType parameter is equal to the string "prod"
  isProduction: !Equals 
    - !Ref EnvType
    - prod
#The Transform section is specifying a custom macro called "MyMacro"
Transform:
  - MyMacro
Resources:
  #LogicalID 
  EC2Instance: 
    #Resource Type
    Type: 'AWS::EC2::Instance' 
    #Specifies the instance can only be created if isProduction is true
    Condition: isProduction
    #Resource Properties
    Properties: 
      InstanceType : m1.small
      #The following property uses the AWS Region psuedo parameter and a !FindInMap intrinsic function
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      UserData:
        Fn::Base64:
        #The following property uses a Fn::Join intrinsic function
          Fn::Join: 
          - "\n"
          - - "#!/bin/bash"
            - sudo yum update -y
            - sudo yum install httpd -y
            - sudo /etc/init.d/httpd start
Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    #The following property uses a !GetAtt intrinsic function
    Value: !GetAtt EC2Instance.PublicIp